apiVersion: v1
kind: Service
metadata:
  name: simple-app
  labels:
    app: simple-app
  
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: simple-app